### ISSUE TITLE
Mark beers that are new at the location

### ISSUE THREAD

**Issue by alefort** [alefort/getcrafty#12]
New would be, added to that location in the last day.

**Comment by scottblinch** [comment]
How would we go about determining this?

**Comment by alefort** [comment]
Night over night I would need to keep previous day's data, then write a
function to see if it was new in the last 7 days.

Very doable. It just means we keep 6 million record in the db instead of 1.

**Comment by scottblinch** [comment]
I've added a badge that will show up on beer.is_new

**Comment by alefort** [comment]
That is just the motivation I needed to get the data setup.

Thanks, you rock.

**Comment by alefort** [comment]
I wrote the first piece of this tonight. The data loader will now keep 7 days of inventory data, and now I have to modify the API calls to handle this extra data

**Comment by alefort** [comment]
This has finally been completed. My god, the first piece of this work started 18 months ago. Time flies.

We now mark beers as new if they were not mentioned in previous inventory records older than 5 days.

@scottblinch Your turn to add this to the f/e views.

**Comment by alefort** [comment]
And just like that, it all works. I wasnt passing the is_new flag in the ProductsAtStore return.
