### ISSUE TITLE
Geolocation poor on home desktops

### ISSUE THREAD

**Issue by alefort** [alefort/getcrafty#17]
What can we do to improve accuracy for devices that aren't on a mobile network, like a laptop on my home network?

**Comment by scottblinch** [comment]
I'm using [ngGeolocation](https://github.com/ninjatronic/ngGeolocation) which is just a wrapper for the [HTML5 Geolocation API](http://www.w3.org/TR/geolocation-API/). If the browser is reporting bad geolocation information we'll have to use something else. What does Jonelle use?

**Comment by alefort** [comment]
Actually. It's not that it's bad, its just ip based and only goes to the
city's downtown. I don't know if it can get any better, the same happens on
jiffy for me
