### ISSUE TITLE
For Products with 1 Inventory

### ISSUE THREAD

**Issue by alefort** [alefort/getcrafty#5]
From what I've learned from the data, products with only 1 unit in inventory are actually empty at the store, but likely being restocked/re-ordered. I'd like to see these records fall to the bottom of the list and perhaps some UI to indicate that beer is a 'maybe' at the store. Any ideas?

**Comment by scottblinch** [comment]
Okay, these are now being sorted to the bottom of the list and have a message saying "Maybe out of stock." What do you think?
