### ISSUE TITLE
Favicon

### ISSUE THREAD

**Issue by alefort** [alefort/getcrafty#6]
Can you make the logo into a favicon like nelson does?

**Comment by scottblinch** [comment]
Ran it through the generator but can't get it to show up on my local for some reason. Can you push the icon update live so I can test there?

**Comment by alefort** [comment]
Pushed. No icons for me.

**Comment by scottblinch** [comment]
Got it working locally. The 16x16 icon just looks like a potato so I'll have to spend some time making a custom one at that size. What do you think of just GC with that umber symbol in the middle?

**Comment by alefort** [comment]
I like the idea. I can ask Kevin if he wants to make a favicon?

**Comment by scottblinch** [comment]
![favicon-16x16](https://cloud.githubusercontent.com/assets/4682114/8894749/ec1a8bfa-338f-11e5-9030-5fb5966ba462.png)

How's this?

**Comment by alefort** [comment]
How about just the red hop from the logo? On a transparent background?

**Comment by scottblinch** [comment]
![favicon-16x16](https://cloud.githubusercontent.com/assets/4682114/8896166/9114c93c-33c1-11e5-9cc5-4f65583e28c9.png)

How's that look?

**Comment by alefort** [comment]
Perfect

**Comment by scottblinch** [comment]
Pushed up. Could you let me know when the favicon update is live so I can test?

**Comment by alefort** [comment]
Live

**Comment by scottblinch** [comment]
Looks good on my browser and phone, what do you think?
