### ISSUE TITLE
Lets add Distance On Store list

### ISSUE THREAD

**Issue by alefort** [alefort/getcrafty#8]
I'll need to return this to you in the api

**Comment by alefort** [comment]
This is now returned in the api call StoresNear. The distance is in meters and is found

Store.location.distance_from_me

Can you please add to the view?

**Comment by scottblinch** [comment]
I've added distance_from_me to the view, but store.location only has latitude and longitude -- maybe the API update wasn't pushed live?

**Comment by alefort** [comment]
you are right. I forgot to restart the api process. Its there now. Can you format it?

**Comment by scottblinch** [comment]
Okay, formatted it to 1 decimal place.
