### ISSUE TITLE
beer.tertiary_category vs beer.varietal

### ISSUE THREAD

**Issue by scottblinch** [alefort/getcrafty#9]
I just noticed a property called varietal coming with the beer data. Wondering if I should be using that instead of tertiary_category. Here's a paste of a few of the beers (tertiary_category is shown first, then varietal):

Staropramen: Pale Lager vs Czech Pilsener
Newcastle Brown Ale: Dark/Brown Ale vs Dark/Brown Ale
Abbot Ale: Bitter vs English Bitter
Mill Street Tankhouse Ale: Pale Ale vs American Pale Ale
Neustadt 10W30 Brown Ale: Dark/Brown Ale vs Dark/Brown Ale
Mill Street Original Organic Lager: Pale Lager vs German Pilsener
Steam Whistle Premium Pilsner: Pale Lager vs Czech Pilsener
Flying Monkeys Hoptical Illusion: Pale Ale vs American Pale Ale

**Comment by alefort** [comment]
You are brilliant. Varietal is more accurate, can you use that?

**Comment by scottblinch** [comment]
Okay, switched that over.

**Comment by scottblinch** [comment]
Discovered that some beers don't have a varietal listed. Some even don't have a tertiary listed. Will have to set up a a function that will try for the varietal, the fallback to the tertiary or secondary when applicable.

**Comment by scottblinch** [comment]
Added the beer style fallback function.
